version: '2'

volumes:
  # Database storage
  globibot-data: {}

services:

  bot:
    build: ./bot
    volumes:
      # Sources
      - './bot:/app:ro'
      # Make the use of the host's docker daemon possible
      - '/var/run/docker.sock:/var/run/docker.sock'
      # Shared host storage (to allow inceptive docker bind mounts)
      - '/tmp/globibot:/tmp/globibot'

  db:
    build: ./db
    volumes:
      # Main data volume
      - 'globibot-data:/var/lib/postgresql/data'

  web:
    build: ./web/server
    volumes:
      # Static web files
      - './web/app:/web'
