version: '2'

volumes:
  globibot-data: {}

services:

  bot:
    build: ./bot
    volumes:
      - './bot/:/app:ro' # Sources
      - '/var/run/docker.sock:/var/run/docker.sock' # Make the use of the host's docker daemon possible
      - '/tmp/globibot:/tmp/globibot' # Shared host storage (to solve inceptive docker volumes issues)

  db:
    build: ./db
    volumes:
      # Main data volume
      - 'globibot-data:/var/lib/postgresql/data'
      # migration system
      - './db/migrate:/flyway/sql'
      - './db/flyway.conf:/flyway/conf/flyway.conf'

  web:
    build: ./web
    ports:
      - '443:443'
    volumes:
      - './web/static:/static:ro'
