version: '2'

volumes:
  globibot-data: {}

services:

  bot:
    build: ./bot
    volumes:
      - './bot/:/app:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'

  db:
    build: ./db
    volumes:
      # Main data volume
      - 'globibot-data:/var/lib/postgresql/data'
      # migration system
      - './db/migrate:/flyway/sql'
      - './db/flyway.conf:/flyway/conf/flyway.conf'

  web:
    image: nginx
    ports:
      - '1337:80'
    volumes:
      - './web/:/web:ro'
      - './web/nginx.conf:/etc/nginx/nginx.conf'
