version: '2'

volumes:
  globibot-data: {}

services:

  bot:
    build: ./bot
    volumes:
      - './bot/:/app:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'

  db:
    image: mongo
    volumes:
      - 'globibot-data:/data/db'
