version: '2'

volumes:
  # Database storage
  globibot-data: {}
  # Bundled website
  globibot-web-dist: {}
  # Dind storage
  dind-data: {}
  # Shared bot storage
  globibot-shared: {}

services:

  bot:
    build: ./bot
    volumes:
      # Sources
      - './bot:/app:ro'
      # Shared host storage
      - './data:/tmp/globibot'
      # Shared storage
      - 'globibot-shared:/tmp/shared'
    environment:
      DOCKER_HOST: 'tcp://dind:2374'

  dind:
    image: 'jpetazzo/dind'
    privileged: true
    stdin_open: true
    volumes:
      - 'dind-data:/var/lib/docker'
      - 'globibot-shared:/bot/mount'
    environment:
      PORT: 2374
      DOCKER_DAEMON_ARGS: "--storage-driver devicemapper --storage-opt dm.override_udev_sync_check=true"

  db:
    build: ./db
    volumes:
      # Main data volume
      - 'globibot-data:/var/lib/postgresql/data'

  web:
    build: ./web/server
    volumes:
      # Static web files
      - 'globibot-web-dist:/web'
