from .animals import AnimalsTrivia
from .capitals import CapitalsTrivia
from .flags import FlagsTrivia
from .pokemons import PokemonsTrivia
from .traps import TrapsTrivia
from .us_states import USStatesTrivia
from .game_releases import GameReleasesTrivia
from .animes import AnimesTrivia
from .programming import ProgrammingTrivia
