bot:
  email: globibot.official@gmail.com
  password: null
  modules:
    hello:    {}
    # twitch:   {}
    # dj:       {}
    # giveaway: {}
    # github:   {}
    # twitter:
    #   consumer_key: null
    #   consumer_secret: null
    #   access_token: null
    #   access_token_secret: null
  masters:
    - 89108411861467136

web:
  port: 8080
