bot:
  token: 'Your bot token'
  plugins:
    foo:    {}
    logger: {}
    meta:   {}
    eval:   {}
    utils:  {}
    stats:  {}
    chat:   {}
    twitch:
      client_id: 'your twitch client id'
    twitter:
      consumer_key: 'your consumer key'
      consumer_secret: 'your consumer secret'
      access_token: 'your access token'
      access_token_secret: 'your access token secret'
    instagram:
      access_token: 'your access token'
      client_secret: 'your client secret'
    help:
      enabled:
        - logger
        - eval
        - utils
        - twitter
        - twitch
        - help
  servers:
    - 'Some server name'
    - 'TestBot'
  masters:
    - 'A valid discord user's snowflake id'

web:
  port: 80

db:
  host: db
  user: postgres
