bot:
  email: globibot.official@gmail.com
  password: null
  modules:
    hello:    {}
    # twitch:   {}
    # dj:       {}
    # giveaway: {}
    # github:   {}
    # eval: {}
    # stats: {}
    # personal:
    #   google_api_key: null
    #   google_search_engine_cx: null
    # twitter:
    #   consumer_key: null
    #   consumer_secret: null
    #   access_token: null
    #   access_token_secret: null
  servers:
    - TestBot
  masters:
    - 89108411861467136

web:
  port: 8080
